Update google-cloudrun-docker.yml

diff --git a/.github/workflows/google-cloudrun-docker.yml b/.github/workflows/google-cloudrun-docker.yml
--- a/.github/workflows/google-cloudrun-docker.yml
+++ b/.github/workflows/google-cloudrun-docker.yml
@@ -156,9 +156,6 @@ jobs:
             responseCode: '200,500'
             timeout: 2000
             interval: 500
-        # If required, use the Cloud Run url output in later steps
-        #- name: Show Output
-         #run: echo ${{ steps.deploy.outputs.url }}
           
         - name: Google Auth
           id: auth
@@ -211,3 +208,45 @@ jobs:
               service: ${{ vars.SERVICE }}
               region: ${{ vars.REGION }}
               image: ${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.SERVICE }}/${{ vars.SERVICE }}:${{ needs.build-push.outputs.git-tag }}
+  test-production:
+      needs: 
+        - build-push
+        - deploy-to-production
+      permissions:
+        id-token: 'write'
+        issues: 'write'
+      environment: prod
+      runs-on: ubuntu-latest
+
+      steps:  
+        - name: Test staging  
+          uses: cygnetdigital/wait_for_response@v2.0.0
+          with:
+            url: 'https://actions-demo-lkxshjwprq-uc.a.run.app/'
+            responseCode: '200,500'
+            timeout: 2000
+            interval: 500
+          
+        - name: Google Auth
+          id: auth
+          uses: 'google-github-actions/auth@v0'
+          with:
+            token_format: 'access_token'
+            workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
+            service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com
+            
+        - name: 'Set up Cloud SDK'
+          uses: 'google-github-actions/setup-gcloud@v1'
+          with:
+            version: '>= 363.0.0'
+
+        - name: 'Use gcloud CLI'
+          id: get-tag
+          run: |
+            echo "tag=$(gcloud run services describe ${{ vars.SERVICE }} --region=${{ vars.REGION }} | grep Image | awk -F: '{print $3}')" >> $GITHUB_OUTPUT
+        
+        - name: Check image version
+          if: ${{steps.get-tag.outputs.tag != needs.build-push.outputs.git-tag }}
+          run: |-
+            echo "Error: Version mismatch, Expected ${{needs.build-push.outputs.git-tag}} but got ${{steps.get-tag.outputs.tag}}"
+            exit 1
